name: CI
on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 26.3
          - 27.2
          - 28.2
          - 29.3
          - release-snapshot
        ignore_warnings:
          - true
        include:
          - emacs_version: snapshot
            ignore_warnings: false
    steps:
    - uses: actions/checkout@v4
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: leotaku/elisp-check@master
      with:
        check: ert
        file: test/ac-dcd-test.el
        ignore_warnings: ${{ matrix.ignore_warnings }}
