name: CI
on: [push, pull_request]

jobs:
  elisp:
    runs-on: ubuntu-22.04   # pinned
    strategy:
      fail-fast: false
      matrix:
        emacs: [27.2, 28.2, 29.4, 30.2]  # current stables

    steps:
      - uses: actions/checkout@v4

      - name: Install Emacs ${{ matrix.emacs }}
        uses: purcell/setup-emacs@v7.0
        with:
          version: ${{ matrix.emacs }}

      # Lint against MELPA requirements (load-file, byte-compile, checkdoc, package-lint)
      - name: MELPA checks
        uses: leotaku/elisp-check@v1.4.1
        with:
          check: melpa
          file: "*.el"

      # Run ERT tests (adjust file/glob to your test entry)
      - name: ERT
        uses: leotaku/elisp-check@v1.4.1
        with:
          check: ert
          file: "test/*.el"
